### ISSUE TITLE
e2e tests crash on nano v1.4.2

### ISSUE THREAD

**Issue by scoriiu** [Neufund/ledger-wallet-provider#29]
Nano firmware version: `1.4.2`

Config:
```
export const config = {
  dp0: "44'/60'/0'/0",
  dp0Acc0: "0x40cE2E6211639f56543013Bc2A7263FBE8F4eea5",
  dp0Acc1: "0xf31766ca2Fb6d4cc9008b573485309a589157bFa",
  dp1: "44'/60'/1'/0",
  dp1Acc0: "0xE9326c84206aD1711dAAB11BC5cD6dE539bec918",
  dp1Acc1: "0xfEae54a7d5554fEDA6e4CbAb02f8Aa4bcAacE9a2",
};
```

Outuput:
```
solo@ledger-wallet-provider$ yarn test-e2e-node
yarn run v1.9.4
$ ./node_modules/.bin/babel-node ./test-e2e/test.js
Signing message "hello world"
{ Error: Invalid sequence
    at maybeWrapAsError (/Users/solo/git/ledger-wallet-provider/node_modules/bluebird/js/release/util.js:61:12)
    at Object.callback (/Users/solo/git/ledger-wallet-provider/node_modules/bluebird/js/release/nodeback.js:38:50)
    at /Users/solo/git/ledger-wallet-provider/node_modules/web3/lib/web3/method.js:142:25
    at /Users/solo/git/ledger-wallet-provider/node_modules/web3/lib/web3/requestmanager.js:82:20
    at /Users/solo/git/ledger-wallet-provider/node_modules/web3-provider-engine/index.js:146:9
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/once.js:12:16
    at replenish (/Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:49:17)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/onlyOnce.js:12:16
    at resultObj.id (/Users/solo/git/ledger-wallet-provider/node_modules/web3-provider-engine/index.js:128:9)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/withoutIndex.js:9:16
    at replenish (/Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:64:17)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:68:9
    at eachLimit (/Users/solo/git/ledger-wallet-provider/node_modules/async/eachLimit.js:43:36)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/solo/git/ledger-wallet-provider/node_modules/web3-provider-engine/index.js:123:5)
  cause: Error: Invalid sequence
    at maybeWrapAsError (/Users/solo/git/ledger-wallet-provider/node_modules/bluebird/js/release/util.js:61:12)
    at Object.callback (/Users/solo/git/ledger-wallet-provider/node_modules/bluebird/js/release/nodeback.js:38:50)
    at /Users/solo/git/ledger-wallet-provider/node_modules/web3/lib/web3/method.js:142:25
    at /Users/solo/git/ledger-wallet-provider/node_modules/web3/lib/web3/requestmanager.js:82:20
    at /Users/solo/git/ledger-wallet-provider/node_modules/web3-provider-engine/index.js:146:9
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/once.js:12:16
    at replenish (/Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:49:17)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/onlyOnce.js:12:16
    at resultObj.id (/Users/solo/git/ledger-wallet-provider/node_modules/web3-provider-engine/index.js:128:9)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/withoutIndex.js:9:16
    at replenish (/Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:64:17)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/eachOfLimit.js:68:9
    at eachLimit (/Users/solo/git/ledger-wallet-provider/node_modules/async/eachLimit.js:43:36)
    at /Users/solo/git/ledger-wallet-provider/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/solo/git/ledger-wallet-provider/node_modules/web3-provider-engine/index.js:123:5),
  isOperational: true }
error Command failed with exit code 1.
```

**Comment by banciur** [comment]
To be hones I don't know what it is. I just tried to run tests locally and they passed. I did run them against newest version that we just published but it shouldn't be the case. We just updated some deps.
